/*   Error and status messages related to the HIER subsystem.
/*
msg err1
  lan english -def
    Invalid indentation level.  Error occurred on line %p1i of file "%p2s".
msg err2
  lan english -def
    Line %p1i of file "%p2s" is at a lower hierarchy level than expected.
msg err3
  lan english -def
    Extra token "%p1s" found on line %p2i of file "%p3s".  The end of line
    was expected.
msg err4
  lan english -def
    Missing parameter on line %p1i of file "%p2s".
msg err5
  lan english -def
    Parameter "%p1s" on line %p2i of file "%p3s" is not a valid integer.
msg err6
  lan english -def
    Parameter "%p1s" on line %p2i of file "%p3s" is not a numeric value.
msg err7
  lan english -def
    Parameter "%p1s" on line %p2i of file "%p3s" is not a boolean value.
msg err8
  lan english -def
    Invalid command "%p1s" on line %p2i of file "%p3s".
msg err9
  lan english -def
    Unrecognized keyword "%p1s" encountered on line %p2i of file "%p3s".
msg err10
  lan english -def
    Parameter "%p1s" on line %p2i of file "%p3s" can not be interpreted as
    an angle.
